In [20]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# File path
data_dir = Path(r"D:\personal projects\humanVsComputerGeneration\Data")
file_path = data_dir / "combined_dataset.csv"

# Load data
combined_clean = pd.read_csv(file_path)

# Define columns
number_cols = [f"number_{i}" for i in range(1, 11)]
label_col = "label"

# Basic overview
print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

print("\nLabel distribution:")
print(df["label"].value_counts().rename(index={
    0: "Computer",
    1: "Human"
}))

Dataset shape: (5848, 11)

First 5 rows:

,number_1,number_2,number_3,number_4,number_5,number_6,number_7,number_8,number_9,number_10,label
0,2,5,3,2,4,8,6,8,9,9,0
1,5,2,6,8,1,7,4,3,2,9,1
2,1,9,8,4,5,5,9,5,7,4,0
3,2,4,3,1,8,7,6,5,9,1,1
4,2,7,6,1,9,8,3,5,6,7,1

Label distribution:
label
Computer    5000
Human        848
Name: count, dtype: int64

In [21]:
# Check dataset dimensions
print("Rows:", len(combined_clean))
print("Columns:", len(combined_clean.columns))

# Check data types, missing values, and unique values
validation_summary = pd.DataFrame({
    "Data Type": combined_clean.dtypes.astype(str),
    "Missing Values": combined_clean.isnull().sum(),
    "Unique Values": combined_clean.nunique()
})

display(validation_summary)

# Check duplicate rows
print("Duplicate rows:", combined_clean.duplicated().sum())

# Check the first 10 rows
display(combined_clean.head(10))
print(combined_clean.shape)

Rows: 5851
Columns: 11

          Data Type  Missing Values  Unique Values
number_1      int64               0              9
number_2      int64               0              9
number_3      int64               0              9
number_4      int64               0              9
number_5      int64               0              9
number_6      int64               0              9
number_7      int64               0              9
number_8      int64               0              9
number_9      int64               0              9
number_10     int64               0              9
label         int64               0              2

Duplicate rows: 3

,number_1,number_2,number_3,number_4,number_5,number_6,number_7,number_8,number_9,number_10,label
0,2,5,3,2,4,8,6,8,9,9,0
1,5,2,6,8,1,7,4,3,2,9,1
2,1,9,8,4,5,5,9,5,7,4,0
3,2,4,3,1,8,7,6,5,9,1,1
4,2,7,6,1,9,8,3,5,6,7,1
5,5,4,2,4,8,6,4,1,4,2,0
6,2,1,1,8,5,9,8,3,8,5,0
7,1,6,1,6,4,3,9,7,6,8,0
8,4,6,6,2,2,3,9,3,6,5,0
9,7,7,9,5,4,2,8,9,1,5,0

(5851, 11)

In [22]:
before = len(combined_clean)
combined_clean.drop_duplicates(inplace=True)
combined_clean.reset_index(drop=True, inplace=True)

# Keep df in sync with the cleaned dataframe
df = combined_clean

print(f"Removed {before - len(combined_clean)} duplicate rows.")
print("New shape:", combined_clean.shape)

Removed 3 duplicate rows.
New shape: (5848, 11)

In [23]:
number_cols = [
    "number_1", "number_2", "number_3", "number_4", "number_5",
    "number_6", "number_7", "number_8", "number_9", "number_10"
]

# Convert to numeric for validation without changing the original data
numbers = combined_clean[number_cols].apply(
    pd.to_numeric, errors="coerce"
)

print("Missing or non-numeric entries:", numbers.isna().sum().sum())
print("Minimum value:", numbers.min().min())
print("Maximum value:", numbers.max().max())

# Count values outside the human range of 1–9
print("Values below 1:", numbers.lt(1).sum().sum())
print("Values above 9:", numbers.gt(9).sum().sum())
print("Non-integer values:", (
    numbers.notna() & numbers.mod(1).ne(0)
).sum().sum())

Missing or non-numeric entries: 0
Minimum value: 1
Maximum value: 9
Values below 1: 0
Values above 9: 0
Non-integer values: 0

In [25]:
output_path = data_dir / "clean_combined_dataset.csv"
combined_clean.to_csv(output_path, index=False)

print(f"Saved cleaned dataset to: {output_path}")

Saved cleaned dataset to: D:\personal projects\humanVsComputerGeneration\Data\clean_combined_dataset.csv